# Generated by Django 3.1.6 on 2021-02-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonspecies',
            options={'verbose_name_plural': 'Pokemon species'},
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolution_level',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
