# Generated by Django 3.1.6 on 2021-02-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20210218_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolution_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='new_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.pokemonspecies'),
        ),
    ]
