# Generated by Django 3.1.6 on 2021-02-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_pokemons_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontype',
            name='pokemon_element',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
