# Generated by Django 3.1.6 on 2021-02-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_auto_20210218_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemons',
            options={'verbose_name_plural': 'Pokemons'},
        ),
        migrations.RenameField(
            model_name='pokemonspecies',
            old_name='pokemon_types',
            new_name='pokemon_type',
        ),
    ]
